export const ADD_INGREDIENT = 'ADD_INGREDIENTS'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENTS'
export const SET_INGREDIENTS = 'SET_INGREDIENTS'
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED"

// Order related action types
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILED = 'PURCHASE_BURGER_FAILED';
export const PURCHASE_BURGER_ASYNC = 'PURCHASE_BURGER_ASYNC';
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT"
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS"
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED"

// Auth related action types
export const AUTH_INIT = "AUTH_INIT"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILURE = "AUTH_FAILURE"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_SET_REDIRECT = "AUTH_SET_REDIRECT"